language: java
install: true
jdk:
- openjdk10
script:
- "./gradlew build -s"
before_install:
- openssl aes-256-cbc -K $encrypted_4f1f482141f0_key -iv $encrypted_4f1f482141f0_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
addons:
  ssh_known_hosts:
    - euclid.srv.kralofsky.com
